require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'pry'
require 'capybara'
require 'colorize'
require 'securerandom'
require_relative 'features/support/browserstack_settings'

ENV['GROUP_SIZE'] ||= '5'
ENV['SERVER_COUNT'] ||= '8'

Cucumber::Rake::Task.new(:run_all, 'Run all features') do |t|
  File.truncate('rerun.txt', 0) if File.exist?('rerun.txt')
  @start_time = Time.now
  t.cucumber_opts = ["--format pretty --retry 1 -f rerun -o rerun.txt DRIVER=#{(ENV['DRIVER']) ? ENV['DRIVER'] : 'headless_chrome'}"]
  t.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
end

Cucumber::Rake::Task.new(:rerun, 'Rerun using rerun.txt') do |t|
  t.cucumber_opts = ["@rerun.txt --format pretty --retry 1 DRIVER=#{(ENV['DRIVER']) ? ENV['DRIVER'] : 'headless_chrome'}"]
  t.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
end

desc 'run all features with rerun'
task :features do
  begin
    Rake::Task['run_all'].invoke
  rescue SystemExit => e
    Rake::Task['rerun'].invoke if Rake.application.top_level_tasks.first == 'features' and !File.read('rerun.txt').empty?
  end
end

at_exit do
  $?.exitstatus == 0 ? (p 'TEST SUITE PASSED') :  (p 'TEST SUITE FAILED')
end
