---
swagger: "2.0"
info:
  description: "MTC Admin API"
  version: "1.0.0"
  title: "MTC Admin API"
  license:
    name: "GPL"
    url: "https://opensource.org/licenses/GPL-3.0"
host: "virtserver.swaggerhub.com"
basePath: "/GuyHarwood/mtc-admin/1.0.0"
tags:
- name: "check data"
  description: "endpoints that pupil app depends upon"
schemes:
- "https"
paths:
  /questions:
    post:
      summary: "returns question set for check"
      description: "By passing in the appropriate options, you can retrieve a set\
        \ of questions\n"
      operationId: "getQuestions"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "pupilDetails"
        description: "Auth Credentials for Pupil taking the check"
        required: false
        schema:
          $ref: "#/definitions/PupilDetails"
      responses:
        200:
          description: "question set returned"
          schema:
            $ref: "#/definitions/PupilCheck"
        400:
          description: "invalid input"
        401:
          description: "unauthorised"
        404:
          description: "question set not found for pupil"
      x-swagger-router-controller: "Default"
definitions:
  PupilDetails:
    type: "object"
    required:
    - "pupilId"
    - "schoolId"
    properties:
      pupilId:
        type: "string"
        example: "abc12345"
      schoolId:
        type: "string"
        example: "9999a"
  PupilCheck:
    type: "object"
    properties:
      questions:
        type: "array"
        items:
          $ref: "#/definitions/Question"
      pupil:
        $ref: "#/definitions/PupilCheck_pupil"
      school:
        $ref: "#/definitions/PupilCheck_school"
  Question:
    type: "object"
    properties:
      rank:
        type: "integer"
        example: 1
        minimum: 1
      factor1:
        type: "integer"
        example: 3
      factor2:
        type: "integer"
        example: 2
  PupilCheck_pupil:
    properties:
      firstName:
        type: "string"
        example: "Morgan"
      lastName:
        type: "string"
        example: "Freeman"
      sessionId:
        type: "string"
      questionTime:
        type: "number"
      loadingTime:
        type: "number"
  PupilCheck_school:
    properties:
      Id:
        type: "integer"
        example: 123456
      name:
        type: "string"
        example: "Hogwarts School of Witchcraft and Wizardry"
    description: "should this be URN?"
