export enum EstablishmentLinkType {
  ChildrensCentreLink = 'CC',
  Closure = '1I',
  Expansion = '2A',
  MergedChangeInAgeRange = '2O',
  MergedExpansionInSchoolCapacityAndChangerInAgeRange = '2Q',
  MergedExpansionOfSchoolCapacity = '2P',
  NotApplicable = '0',
  Other = '9',
  PredecessorAmalgamated = '6.1',
  Predecessor = '1',
  PredecessorMerged = '1L',
  PredecessorSplitSchool = '1F',
  ResultOfAmalgamation = '2K',
  SixthFormCentreLink = '4',
  SixthFormCentreSchool = '5',
  Successor = '2',
  SuccessorAmalgamated = '6.2',
  SuccessorMerged = '6',
  SuccessorSplitSchool = '2F'
}
