# AzureDevops build defintion for Azure services key rotation and key vault update
resources:
  - repo: self

name: Azure-Key-Rotation-$(date:yyyyMMdd)$(rev:.r)

variables:
- name: buildAgentPool
  value: MTC

parameters:
- name:         keyType
  displayName:  Which Key to Renew (if applicable)
  type:         string
  default:      primary
  values:
  - primary
  - secondary

- name:         serviceBusUser
  displayName:  service bus user id for consumer
  type:         string
  default:      mtc-consumer

- name:         keyVaultName
  displayName:  name of key vault to update
  type:         string

- name:         resourceGroupName
  displayName:  target resource group
  type:         string

- name:         redisName
  displayName:  target redis instance
  type:         string

- name:         serviceBusName
  displayName:  target service bus instance
  type:         string

- name:         storageAccountName
  displayName:  target storage account
  type:         string

# do not trigger automatically
trigger: none

pool:
  name: $(buildAgentPool)

jobs:
- job: RedisKey
  steps:
  - task: AzureCLI@2
    displayName: renew Redis Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/redis.sh'
      arguments: ${{ parameters.resourceGroupName }} ${{ parameters.keyVaultName }} ${{ parameters.redisName }} ${{ parameters.keyType }}
      failOnStandardError: true
- job: ServiceBusKey
  steps:
  - task: AzureCLI@2
    displayName: renew Service Bus Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/service-bus.sh'
      arguments: ${{ parameters.resourceGroupName }} ${{ parameters.keyVaultName }} ${{ parameters.serviceBusName }} ${{ parameters.keyType }} ${{ parameters.serviceBusUser }}
      failOnStandardError: true
- job: StorageAccountKey
  steps:
  - task: AzureCLI@2
    displayName: renew Storage Account Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/storage.sh'
      arguments: ${{ parameters.resourceGroupName }} ${{ parameters.keyVaultName }} ${{ parameters.storageAccountName }} ${{ parameters.keyType }}
      failOnStandardError: true
- job: ExpressSessionSecret
  steps:
  - task: AzureCLI@2
    displayName: renew express session secret
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/express-session.sh'
      arguments: ${{ parameters.keyVaultName }}
      failOnStandardError: true
