# AzureDevops build defintion for Azure services key rotation and key vault update
resources:
  - repo: self

name: Azure-Key-Rotation-$(date:yyyyMMdd)$(rev:.r)

variables:
- name:         BuildAgentPool
  value:        MTC
- name:         KeyVaultName
  value:        ''
- name:         RedisName
  value:        ''
- name:         ResourceGroupName
  value:        ''
- name:         ServiceBusName
  value:        ''
- name:         ServiceBusUser
  value:        mtc-consumer
- name:         StorageAccountName
  value:        ''

parameters:
- name:         keyType
  displayName:  Which Key to Renew (if applicable)
  type:         string
  default:      primary
  values:
  - primary
  - secondary


# do not trigger automatically
trigger: none

pool:
  name: $(BuildAgentPool)

jobs:
- job: RedisKey
  steps:
  - task: AzureCLI@2
    displayName: renew Redis Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/redis.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(RedisName) ${{ parameters.keyType }}
      failOnStandardError: true
- job: ServiceBusKey
  steps:
  - task: AzureCLI@2
    displayName: renew Service Bus Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/service-bus.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(ServiceBusName) ${{ parameters.keyType }} $(ServiceBusUser)
      failOnStandardError: true
- job: StorageAccountKey
  steps:
  - task: AzureCLI@2
    displayName: renew Storage Account Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/storage.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(StorageAccountName) ${{ parameters.keyType }}
      failOnStandardError: true
- job: ExpressSessionSecret
  steps:
  - task: AzureCLI@2
    displayName: renew express session secret
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/keys/express-session.sh'
      arguments: $(KeyVaultName)
      failOnStandardError: true
