apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-dev
  name: admin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-dev
    spec:
      containers:
      - args:
        - ./wait-for-db.sh
        - sqldb
        - ./docker-start-dev.sh
        env:
        - name: REDIS_HOST
          value: redis
        - name: SQL_SERVER
          value: sqldb
        image: admin-dev
        imagePullPolicy: ""
        name: mtc-admin-dev
        ports:
        - containerPort: 3001
        resources: {}
        volumeMounts:
        - mountPath: /mtc
          name: admin-dev-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: admin-dev-claim0
        persistentVolumeClaim:
          claimName: admin-dev-claim0
status: {}
