resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

variables:
  var1: value1

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

jobs:
- job: FastFail
  steps:
- task: ShellScript@2
    scriptPath: 'deploy/pr-label-check.sh'
    args: '$(System.PullRequest.PullRequestNumber)'
    failOnStandardError: true
    displayName: 'Fail if CI Enabled label not applied to PR'
- job: Generate
  dependsOn: FastFail
  steps:
    - task: ShellScript@2
    displayName: 'generate build and commit details file'
    inputs:
      scriptPath: 'admin/vso-add-build-and-commit.sh'
      failOnStandardError: true

