version: '3'
services:
  mongo:
    image: mongo
    container_name: mtc_mongo
    ports:
    - "27017:27017"
  sqldb:
    image: "microsoft/mssql-server-linux:2017-GDR"
    container_name: mtc_mssql
    ports:
    - "1433:1433"
    environment:
        SA_PASSWORD: "Mtc-D3v.5ql_S3rv3r"
        ACCEPT_EULA: "Y"
        HOMEBREW_NO_ENV_FILTERING: 1
  admin-tests:
    build: ./test
    container_name: admin_tests
    depends_on:
    - mongo
    - sqldb
    - admin-app
    links:
    - sqldb
    - admin-app
    - mongo
  admin-app:
    build: ./admin
    container_name: mtc_admin
    ports:
    - "3001:3001"
    volumes:
    - ./admin:/usr/src/app
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongo/mtc"
    depends_on:
    - sqldb
    - mongo
    links:
    - sqldb
    - mongo