INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (0, N'Does not apply');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (201, N'City of London');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (202, N'Camden');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (203, N'Greenwich');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (204, N'Hackney');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (205, N'Hammersmith and Fulham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (206, N'Islington');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (207, N'Kensington and Chelsea');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (208, N'Lambeth');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (209, N'Lewisham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (210, N'Southwark');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (211, N'Tower Hamlets');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (212, N'Wandsworth');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (213, N'Westminster');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (301, N'Barking and Dagenham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (302, N'Barnet');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (303, N'Bexley');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (304, N'Brent');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (305, N'Bromley');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (306, N'Croydon');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (307, N'Ealing');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (308, N'Enfield');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (309, N'Haringey');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (310, N'Harrow');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (311, N'Havering');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (312, N'Hillingdon');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (313, N'Hounslow');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (314, N'Kingston upon Thames');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (315, N'Merton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (316, N'Newham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (317, N'Redbridge');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (318, N'Richmond upon Thames');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (319, N'Sutton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (320, N'Waltham Forest');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (330, N'Birmingham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (331, N'Coventry');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (332, N'Dudley');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (333, N'Sandwell');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (334, N'Solihull');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (335, N'Walsall');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (336, N'Wolverhampton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (340, N'Knowsley');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (341, N'Liverpool');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (342, N'St. Helens');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (343, N'Sefton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (344, N'Wirral');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (350, N'Bolton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (351, N'Bury');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (352, N'Manchester');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (353, N'Oldham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (354, N'Rochdale');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (355, N'Salford');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (356, N'Stockport');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (357, N'Tameside');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (358, N'Trafford');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (359, N'Wigan');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (370, N'Barnsley');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (371, N'Doncaster');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (372, N'Rotherham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (373, N'Sheffield');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (380, N'Bradford');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (381, N'Calderdale');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (382, N'Kirklees');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (383, N'Leeds');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (384, N'Wakefield');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (390, N'Gateshead');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (391, N'Newcastle upon Tyne');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (392, N'North Tyneside');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (393, N'South Tyneside');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (394, N'Sunderland');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (420, N'Isles Of Scilly');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (660, N'Isle of Anglesey');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (661, N'Gwynedd');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (662, N'Conwy');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (663, N'Denbighshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (664, N'Flintshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (665, N'Wrexham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (666, N'Powys');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (667, N'Ceredigion');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (668, N'Pembrokeshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (669, N'Carmarthenshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (670, N'Swansea');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (671, N'Neath Port Talbot');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (672, N'Bridgend');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (673, N'Vale of Glamorgan');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (674, N'Rhondda Cynon Taf');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (675, N'Merthyr Tydfil');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (676, N'Caerphilly');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (677, N'Blaenau Gwent');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (678, N'Torfaen');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (679, N'Monmouthshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (680, N'Newport');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (681, N'Cardiff');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (701, N'Scotland Offshore Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (702, N'BFPO Overseas Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (704, N'Fieldwork Overseas Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (705, N'Isle of Man Offshore Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (706, N'Guernsey Offshore Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (707, N'Jersey Offshore Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (708, N'Gibraltar Overseas Establishments');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (800, N'Bath and North East Somerset');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (801, N'Bristol, City of');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (802, N'North Somerset');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (803, N'South Gloucestershire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (805, N'Hartlepool');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (806, N'Middlesbrough');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (807, N'Redcar and Cleveland');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (808, N'Stockton-on-Tees');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (810, N'Kingston upon Hull, City of');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (811, N'East Riding of Yorkshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (812, N'North East Lincolnshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (813, N'North Lincolnshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (815, N'North Yorkshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (816, N'York');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (821, N'Luton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (822, N'Bedford');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (823, N'Central Bedfordshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (825, N'Buckinghamshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (826, N'Milton Keynes');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (830, N'Derbyshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (831, N'Derby');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (835, N'Pre-LGR 2019 Dorset');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (836, N'Pre-LGR 2019 Poole');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (837, N'Pre-LGR 2019 Bournemouth');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (838, N'Dorset');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (839, N'Bournemouth, Christchurch and Poole');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (840, N'County Durham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (841, N'Darlington');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (845, N'East Sussex');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (846, N'Brighton and Hove');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (850, N'Hampshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (851, N'Portsmouth');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (852, N'Southampton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (855, N'Leicestershire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (856, N'Leicester');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (857, N'Rutland');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (860, N'Staffordshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (861, N'Stoke-on-Trent');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (865, N'Wiltshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (866, N'Swindon');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (867, N'Bracknell Forest');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (868, N'Windsor and Maidenhead');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (869, N'West Berkshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (870, N'Reading');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (871, N'Slough');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (872, N'Wokingham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (873, N'Cambridgeshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (874, N'Peterborough');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (876, N'Halton');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (877, N'Warrington');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (878, N'Devon');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (879, N'Plymouth');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (880, N'Torbay');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (881, N'Essex');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (882, N'Southend-on-Sea');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (883, N'Thurrock');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (884, N'Herefordshire, County of');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (885, N'Worcestershire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (886, N'Kent');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (887, N'Medway');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (888, N'Lancashire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (889, N'Blackburn with Darwen');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (890, N'Blackpool');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (891, N'Nottinghamshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (892, N'Nottingham');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (893, N'Shropshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (894, N'Telford and Wrekin');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (895, N'Cheshire East');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (896, N'Cheshire West and Chester');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (908, N'Cornwall');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (909, N'Cumbria');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (916, N'Gloucestershire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (919, N'Hertfordshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (921, N'Isle of Wight');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (925, N'Lincolnshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (926, N'Norfolk');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (928, N'Northamptonshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (929, N'Northumberland');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (931, N'Oxfordshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (933, N'Somerset');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (935, N'Suffolk');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (936, N'Surrey');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (937, N'Warwickshire');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (938, N'West Sussex');
INSERT INTO mtc_admin.laCodeLookup (laCode, laName) VALUES (999, N'Test');
