swagger: '2.0'
info:
  description: Receives completed check payloads
  version: 1.1.1
  title: MTC Check API
  license:
    name: GPL
    url: 'https://opensource.org/licenses/GPL-3.0'
tags:
  - name: check
    description: endpoints that pupil app depends upon
paths:
  /api/completed-check:
    post:
      summary: persists completed pupil check
      description: >
        By passing in the appropriate options, you can retrieve a set of
        questions
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: checkPayload
          description: The completed check data
          schema:
            $ref: '#/definitions/CompletedCheck'
      responses:
        '201':
          description: created
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Unauthorised
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    required:
      - text
    properties:
      text:
        type: string
        example: error
  CompletedCheck:
    type: object
    required:
      - answers
      - inputs
      - audit
      - config
      - access_token
    properties:
      answers:
        type: array
        items:
          $ref: '#definitions/Answer'
      inputs:
        type: array
        items:
          $ref: '#defintions/Inputs'
      audit:
        type: array
        items:
          $ref: '#defintions/Audit'
      access_token:
        type: string
        example: ksdfbegkhsdfkuh34888d8ej4dhjd
  Answer:
    type: object
    properties:
      factor1:
        type: integer
        example: 3
        description: the left hand part of the question
      factor2:
        type: integer
        example: 2
        description: the right hand part of the question
      answer:
        type: integer
        minimum: 1
        example: 1
        description: the answer to the question
  Inputs:
    type: object
    properties:
      inputType:
        type: string
        example: mouse_click
      data:
        type: string
        example: '7'
      clientTimestamp:
        type: string
        example: '2017-08-22 12:53:02.139Z'
  Audit:
    type: object
    properties:
      auditType:
        type: string
        example: Check_Started
      clientTimestamp:
        type: string
        example: '2017-08-22 12:53:02.139Z'
      data:
        type: object
        description: any data structure relevant to the audit entry
schemes:
  - https
