trigger: none

pool:
  name: 'Azure Pipelines'

steps:
- task: AzureCLI@2
  displayName: 'Add Build Server IPv4 Address to PreProd KeyVault'
  inputs:
    azureSubscription: $(PreProdServiceConnection)
    scriptType: bash
    scriptPath: 'deploy/build-defs/add-key-vault-ip.sh'
    arguments: $(PreProdKeyVaultName) $(PreProdResourceGroup) $(IpAddress) $(IpAddress2) $(IpAddress3)
- task: AzureCLI@2
  displayName: 'Add Build Server IPv4 Address to Prod KeyVault'
  inputs:
    azureSubscription: $(ProdServiceConnection)
    scriptType: bash
    scriptPath: 'deploy/build-defs/add-key-vault-ip.sh'
    arguments: $(ProdKeyVaultName) $(ProdResourceGroup) $(IpAddress) $(IpAddress2) $(IpAddress3)
