require 'cucumber/rake/task'
require_relative '../test/features/support/browserstack_settings'

BrowserstackSettings.browser_caps.keys.each_with_index do |browser, index|
  Cucumber::Rake::Task.new("bs_#{browser}".to_sym) do |task|
    task.cucumber_opts = "--format=pretty DRIVER=bs_#{browser} -f rerun -o rerun.txt"
    task.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
  end
end

desc 're run failing test'
Cucumber::Rake::Task.new :failing_tests, 'Re-run failing tests from the rerun.txt file' do |t|
  t.cucumber_opts = "@rerun.txt -f pretty DRIVER=#{(Rake.application.top_level_tasks.first == 'features') ? 'poltergeist' : Rake.application.top_level_tasks.first}"
end

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "--format pretty -f rerun -o rerun.txt DRIVER=poltergeist"
  t.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
end

at_exit do
  Rake::Task[:failing_tests].invoke unless File.read('rerun.txt').empty?
end
