DELETE FROM mtc_admin.adminLogonEvent;
DELETE FROM mtc_admin.pupilLogonEvent;
UPDATE mtc_admin.school SET pin=NULL;
DELETE FROM mtc_admin.pupilFeedback;
DELETE FROM mtc_admin.psychometricianReportCache;
DELETE FROM mtc_admin.[checkPin];
DELETE FROM mtc_admin.[check];
DELETE FROM mtc_admin.answer;
DELETE FROM mtc_admin.sessions;
DELETE FROM mtc_admin.auditLog;
UPDATE mtc_admin.pupil SET pupilStatus_id = 1;
DELETE FROM mtc_results.userDevice;
DELETE FROM mtc_results.event;
DELETE FROM mtc_results.userInput;
DELETE FROM mtc_results.answer;
DELETE FROM mtc_results.checkResult;