version: '3'
services:
  sqldb:
    image: "mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04"
    container_name: mtc_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mtc-D3v.5ql_S3rv3r"
      ACCEPT_EULA: "Y"
      HOMEBREW_NO_ENV_FILTERING: 1
  redis:
    image: "redis:4.0-alpine"
    container_name: mtc_redis
    ports:
      - "6379:6379"
  dbmigration:
    build:
      context: ../../db
      dockerfile: dev.Dockerfile
    container_name: mtc_db_migrations_reg_test
    environment:
      SQL_SERVER: 'sqldb'
      SQL_PORT: '1433'
    depends_on:
      - sqldb
  func_throttled:
    build:
      context: ../../func-throttled
      dockerfile: test.Dockerfile
    container_name: mtc_func_throttled_reg_test
    ports:
      - 7073:7073
    environment:
      SQL_SERVER: 'sqldb'
      REDIS_HOST: 'redis'
    depends_on:
      - sqldb
      - dbmigration
      - redis
    command: ["./wait-for-db.sh", "sqldb", "yarn", "start"]
  func_consumption:
    build:
      context: ../../func-consumption
      dockerfile: test.Dockerfile
    container_name: mtc_func_consumption_reg_test
    ports:
      - 7071:7071
    environment:
      SQL_SERVER: 'sqldb'
      REDIS_HOST: 'redis'
    depends_on:
      - sqldb
      - dbmigration
      - redis
    command: ["./wait-for-db.sh", "sqldb", "yarn", "start"]
  admin:
      build:
        context: ../../admin
      container_name: mtc_admin_reg_test
      ports:
        - 3001:3001
      environment:
        SQL_SERVER: 'sqldb'
        REDIS_HOST: 'redis'
      depends_on:
        - sqldb
        - dbmigration
        - redis
      restart: always
      command: ["./wait-for-db.sh", "sqldb", "./docker-start-dev.sh"]
  spa:
    build:
      context: ../../pupil-spa
    container_name: mtc_spa_reg_test
    ports:
      - 4200:4200
    environment:
      REDIS_HOST: 'redis'
    command: ["./docker-start-dev.sh"]
  pupil_api:
    build:
      context: ../../pupil-api
    container_name: mtc_pupil_api_reg_test
    ports:
      - 3003:3003
    environment:
      REDIS_HOST: 'redis'
    depends_on:
      - redis
    volumes:
      - "./:/mtc"
    command: ["./docker-start-dev.sh"]
