  # It is currently not possible to easily source the IP of a container instance
  # This build task solves that problem by echoing it to the output stream
  # USAGE
  # =====
  # the pool.demands section allows you to target a specific build server instance
  # NOTE: ensure this custom demand is added to each build server, and has a unique matching value

trigger: none

pool:
  name: 'MTC'
  demands:
  - mtc-instance -equals $(MTC_INSTANCE)

steps:
- script: echo $(curl 'https://api.ipify.org?format=json')
  displayName: 'Reveal IPv4 Address'
