ALTER TABLE mtc_admin.checkWindow ALTER COLUMN adminEndDate datetimeoffset
ALTER TABLE mtc_admin.checkWindow ALTER COLUMN familiarisationCheckStartDate datetimeoffset
ALTER TABLE mtc_admin.checkWindow ALTER COLUMN familiarisationCheckEndDate datetimeoffset
