DROP INDEX IF EXISTS [mtc_admin].[pupilAccessArrangements].[pupilAccessArrangements_questionReaderReasons_id_index]
DROP INDEX IF EXISTS [mtc_admin].[pupilAccessArrangements].[pupilAccessArrangements_pupil_id_index]
DROP INDEX IF EXISTS [mtc_admin].[pupilAccessArrangements].[pupilAccessArrangements_accessArrangements_id_index]
DROP INDEX IF EXISTS [mtc_admin].[pupilAccessArrangements].[pupilAccessArrangements_pupilFontSizes_id_index]
DROP INDEX IF EXISTS [mtc_admin].[pupilAccessArrangements].[pupilAccessArrangements_pupilColourContrasts_id_index]
