require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'pry'
require 'capybara'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "--format pretty -f rerun -o rerun.txt DRIVER=poltergeist"
  t.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
end

desc 're run failing test'
Cucumber::Rake::Task.new :failing_tests, 'Re-run failing tests from the rerun.txt file' do |t|
  t.cucumber_opts = "@rerun.txt -f pretty DRIVER=poltergeist"
end

at_exit do
  begin
    Rake::Task[:failing_tests].invoke unless File.read('rerun.txt').empty?
  rescue Exception => e
    puts "#{e.class}: #{e.message}"
  end
  puts "THE EXIT STATUS CODE IS: #{$?.exitstatus}"
end


