require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'pry'
require 'capybara'

File.truncate('rerun.txt', 0) if File.exist?('rerun.txt')

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "--format pretty -f rerun -o rerun.txt DRIVER=#{(ENV['DRIVER']) ? ENV['DRIVER'] : 'headless_chrome'}"
  t.cucumber_opts << " #{ENV['OPTS']}" unless ENV['OPTS'].nil?
end

desc 're run failing test'
Cucumber::Rake::Task.new :failing_tests, 'Re-run failing tests from the rerun.txt file' do |t|
  t.cucumber_opts = "@rerun.txt -f pretty DRIVER=#{(ENV['DRIVER']) ? ENV['DRIVER'] : 'headless_chrome'}"
end

at_exit do
  begin
    puts "\n**** RE RUNNING FAILING TESTS ****\n\n" unless File.read('rerun.txt').empty?
    Rake::Task[:failing_tests].invoke unless File.read('rerun.txt').empty?
  rescue Exception => e
    puts "#{e.class}: #{e.message}"
  end
  puts "THE EXIT STATUS CODE IS: #{$?.exitstatus}"
  exit $?.exitstatus
end
