export interface PsychometricReport {
  PupilId: number
  PupilUPN: string
  createdAt: moment.Moment | null
  updatedAt: moment.Moment | null
  DOB: moment.Moment | null
  Gender: string | null
  Forename: string | null
  Surname: string | null
  FormMark: number | null
  QDisplayTime: number | null
  PauseLength: number | null
  AccessArr: string | null
  RestartReason: string | null
  RestartNumber: number | null
  ReasonNotTakingCheck: number | null
  PupilStatus: string | null
  DeviceId: string | null
  BrowserType: string | null
  SchoolName: string | null
  Estab: number | null
  SchoolURN: number | null
  LANum: number | null
  AttemptId: string | null
  FormID: string | null
  TestDate: moment.Moment | null
  TimeStart: moment.Moment | null
  TimeComplete: moment.Moment | null
  TimeTaken: number | null
  ToECode: number | null
  ImportedFromCensus: boolean

  // Questions

  Q1ID: string | null
  Q1Response: string | null
  Q1InputMethods: string | null
  Q1K: string | null
  Q1Sco: number | null
  Q1ResponseTime: number | null
  Q1TimeOut: number | null
  Q1TimeOutResponse: number | null
  Q1TimeOutSco: number | null
  Q1tLoad: moment.Moment | null
  Q1tFirstKey: moment.Moment | null
  Q1tLastKey: moment.Moment | null
  Q1OverallTime: number | null
  Q1RecallTime: number | null
  Q1ReaderStart: moment.Moment | null
  Q1ReaderEnd: moment.Moment | null

  Q2ID: string | null
  Q2Response: string | null
  Q2InputMethods: string | null
  Q2K: string | null
  Q2Sco: number | null
  Q2ResponseTime: number | null
  Q2TimeOut: number | null
  Q2TimeOutResponse: number | null
  Q2TimeOutSco: number | null
  Q2tLoad: moment.Moment | null
  Q2tFirstKey: moment.Moment | null
  Q2tLastKey: moment.Moment | null
  Q2OverallTime: number | null
  Q2RecallTime: number | null
  Q2ReaderStart: moment.Moment | null
  Q2ReaderEnd: moment.Moment | null

  Q3ID: string | null
  Q3Response: string | null
  Q3InputMethods: string | null
  Q3K: string | null
  Q3Sco: number | null
  Q3ResponseTime: number | null
  Q3TimeOut: number | null
  Q3TimeOutResponse: number | null
  Q3TimeOutSco: number | null
  Q3tLoad: moment.Moment | null
  Q3tFirstKey: moment.Moment | null
  Q3tLastKey: moment.Moment | null
  Q3OverallTime: number | null
  Q3RecallTime: number | null
  Q3ReaderStart: moment.Moment | null
  Q3ReaderEnd: moment.Moment | null

  Q4ID: string | null
  Q4Response: string | null
  Q4InputMethods: string | null
  Q4K: string | null
  Q4Sco: number | null
  Q4ResponseTime: number | null
  Q4TimeOut: number | null
  Q4TimeOutResponse: number | null
  Q4TimeOutSco: number | null
  Q4tLoad: moment.Moment | null
  Q4tFirstKey: moment.Moment | null
  Q4tLastKey: moment.Moment | null
  Q4OverallTime: number | null
  Q4RecallTime: number | null
  Q4ReaderStart: moment.Moment | null
  Q4ReaderEnd: moment.Moment | null

  Q5ID: string | null
  Q5Response: string | null
  Q5InputMethods: string | null
  Q5K: string | null
  Q5Sco: number | null
  Q5ResponseTime: number | null
  Q5TimeOut: number | null
  Q5TimeOutResponse: number | null
  Q5TimeOutSco: number | null
  Q5tLoad: moment.Moment | null
  Q5tFirstKey: moment.Moment | null
  Q5tLastKey: moment.Moment | null
  Q5OverallTime: number | null
  Q5RecallTime: number | null
  Q5ReaderStart: moment.Moment | null
  Q5ReaderEnd: moment.Moment | null

  Q6ID: string | null
  Q6Response: string | null
  Q6InputMethods: string | null
  Q6K: string | null
  Q6Sco: number | null
  Q6ResponseTime: number | null
  Q6TimeOut: number | null
  Q6TimeOutResponse: number | null
  Q6TimeOutSco: number | null
  Q6tLoad: moment.Moment | null
  Q6tFirstKey: moment.Moment | null
  Q6tLastKey: moment.Moment | null
  Q6OverallTime: number | null
  Q6RecallTime: number | null
  Q6ReaderStart: moment.Moment | null
  Q6ReaderEnd: moment.Moment | null

  Q7ID: string | null
  Q7Response: string | null
  Q7InputMethods: string | null
  Q7K: string | null
  Q7Sco: number | null
  Q7ResponseTime: number | null
  Q7TimeOut: number | null
  Q7TimeOutResponse: number | null
  Q7TimeOutSco: number | null
  Q7tLoad: moment.Moment | null
  Q7tFirstKey: moment.Moment | null
  Q7tLastKey: moment.Moment | null
  Q7OverallTime: number | null
  Q7RecallTime: number | null
  Q7ReaderStart: moment.Moment | null
  Q7ReaderEnd: moment.Moment | null

  Q8ID: string | null
  Q8Response: string | null
  Q8InputMethods: string | null
  Q8K: string | null
  Q8Sco: number | null
  Q8ResponseTime: number | null
  Q8TimeOut: number | null
  Q8TimeOutResponse: number | null
  Q8TimeOutSco: number | null
  Q8tLoad: moment.Moment | null
  Q8tFirstKey: moment.Moment | null
  Q8tLastKey: moment.Moment | null
  Q8OverallTime: number | null
  Q8RecallTime: number | null
  Q8ReaderStart: moment.Moment | null
  Q8ReaderEnd: moment.Moment | null

  Q9ID: string | null
  Q9Response: string | null
  Q9InputMethods: string | null
  Q9K: string | null
  Q9Sco: number | null
  Q9ResponseTime: number | null
  Q9TimeOut: number | null
  Q9TimeOutResponse: number | null
  Q9TimeOutSco: number | null
  Q9tLoad: moment.Moment | null
  Q9tFirstKey: moment.Moment | null
  Q9tLastKey: moment.Moment | null
  Q9OverallTime: number | null
  Q9RecallTime: number | null
  Q9ReaderStart: moment.Moment | null
  Q9ReaderEnd: moment.Moment | null

  Q10ID: string | null
  Q10Response: string | null
  Q10InputMethods: string | null
  Q10K: string | null
  Q10Sco: number | null
  Q10ResponseTime: number | null
  Q10TimeOut: number | null
  Q10TimeOutResponse: number | null
  Q10TimeOutSco: number | null
  Q10tLoad: moment.Moment | null
  Q10tFirstKey: moment.Moment | null
  Q10tLastKey: moment.Moment | null
  Q10OverallTime: number | null
  Q10RecallTime: number | null
  Q10ReaderStart: moment.Moment | null
  Q10ReaderEnd: moment.Moment | null

  Q11ID: string | null
  Q11Response: string | null
  Q11InputMethods: string | null
  Q11K: string | null
  Q11Sco: number | null
  Q11ResponseTime: number | null
  Q11TimeOut: number | null
  Q11TimeOutResponse: number | null
  Q11TimeOutSco: number | null
  Q11tLoad: moment.Moment | null
  Q11tFirstKey: moment.Moment | null
  Q11tLastKey: moment.Moment | null
  Q11OverallTime: number | null
  Q11RecallTime: number | null
  Q11ReaderStart: moment.Moment | null
  Q11ReaderEnd: moment.Moment | null

  Q12ID: string | null
  Q12Response: string | null
  Q12InputMethods: string | null
  Q12K: string | null
  Q12Sco: number | null
  Q12ResponseTime: number | null
  Q12TimeOut: number | null
  Q12TimeOutResponse: number | null
  Q12TimeOutSco: number | null
  Q12tLoad: moment.Moment | null
  Q12tFirstKey: moment.Moment | null
  Q12tLastKey: moment.Moment | null
  Q12OverallTime: number | null
  Q12RecallTime: number | null
  Q12ReaderStart: moment.Moment | null
  Q12ReaderEnd: moment.Moment | null

  Q13ID: string | null
  Q13Response: string | null
  Q13InputMethods: string | null
  Q13K: string | null
  Q13Sco: number | null
  Q13ResponseTime: number | null
  Q13TimeOut: number | null
  Q13TimeOutResponse: number | null
  Q13TimeOutSco: number | null
  Q13tLoad: moment.Moment | null
  Q13tFirstKey: moment.Moment | null
  Q13tLastKey: moment.Moment | null
  Q13OverallTime: number | null
  Q13RecallTime: number | null
  Q13ReaderStart: moment.Moment | null
  Q13ReaderEnd: moment.Moment | null

  Q14ID: string | null
  Q14Response: string | null
  Q14InputMethods: string | null
  Q14K: string | null
  Q14Sco: number | null
  Q14ResponseTime: number | null
  Q14TimeOut: number | null
  Q14TimeOutResponse: number | null
  Q14TimeOutSco: number | null
  Q14tLoad: moment.Moment | null
  Q14tFirstKey: moment.Moment | null
  Q14tLastKey: moment.Moment | null
  Q14OverallTime: number | null
  Q14RecallTime: number | null
  Q14ReaderStart: moment.Moment | null
  Q14ReaderEnd: moment.Moment | null

  Q15ID: string | null
  Q15Response: string | null
  Q15InputMethods: string | null
  Q15K: string | null
  Q15Sco: number | null
  Q15ResponseTime: number | null
  Q15TimeOut: number | null
  Q15TimeOutResponse: number | null
  Q15TimeOutSco: number | null
  Q15tLoad: moment.Moment | null
  Q15tFirstKey: moment.Moment | null
  Q15tLastKey: moment.Moment | null
  Q15OverallTime: number | null
  Q15RecallTime: number | null
  Q15ReaderStart: moment.Moment | null
  Q15ReaderEnd: moment.Moment | null

  Q16ID: string | null
  Q16Response: string | null
  Q16InputMethods: string | null
  Q16K: string | null
  Q16Sco: number | null
  Q16ResponseTime: number | null
  Q16TimeOut: number | null
  Q16TimeOutResponse: number | null
  Q16TimeOutSco: number | null
  Q16tLoad: moment.Moment | null
  Q16tFirstKey: moment.Moment | null
  Q16tLastKey: moment.Moment | null
  Q16OverallTime: number | null
  Q16RecallTime: number | null
  Q16ReaderStart: moment.Moment | null
  Q16ReaderEnd: moment.Moment | null

  Q17ID: string | null
  Q17Response: string | null
  Q17InputMethods: string | null
  Q17K: string | null
  Q17Sco: number | null
  Q17ResponseTime: number | null
  Q17TimeOut: number | null
  Q17TimeOutResponse: number | null
  Q17TimeOutSco: number | null
  Q17tLoad: moment.Moment | null
  Q17tFirstKey: moment.Moment | null
  Q17tLastKey: moment.Moment | null
  Q17OverallTime: number | null
  Q17RecallTime: number | null
  Q17ReaderStart: moment.Moment | null
  Q17ReaderEnd: moment.Moment | null

  Q18ID: string | null
  Q18Response: string | null
  Q18InputMethods: string | null
  Q18K: string | null
  Q18Sco: number | null
  Q18ResponseTime: number | null
  Q18TimeOut: number | null
  Q18TimeOutResponse: number | null
  Q18TimeOutSco: number | null
  Q18tLoad: moment.Moment | null
  Q18tFirstKey: moment.Moment | null
  Q18tLastKey: moment.Moment | null
  Q18OverallTime: number | null
  Q18RecallTime: number | null
  Q18ReaderStart: moment.Moment | null
  Q18ReaderEnd: moment.Moment | null

  Q19ID: string | null
  Q19Response: string | null
  Q19InputMethods: string | null
  Q19K: string | null
  Q19Sco: number | null
  Q19ResponseTime: number | null
  Q19TimeOut: number | null
  Q19TimeOutResponse: number | null
  Q19TimeOutSco: number | null
  Q19tLoad: moment.Moment | null
  Q19tFirstKey: moment.Moment | null
  Q19tLastKey: moment.Moment | null
  Q19OverallTime: number | null
  Q19RecallTime: number | null
  Q19ReaderStart: moment.Moment | null
  Q19ReaderEnd: moment.Moment | null

  Q20ID: string | null
  Q20Response: string | null
  Q20InputMethods: string | null
  Q20K: string | null
  Q20Sco: number | null
  Q20ResponseTime: number | null
  Q20TimeOut: number | null
  Q20TimeOutResponse: number | null
  Q20TimeOutSco: number | null
  Q20tLoad: moment.Moment | null
  Q20tFirstKey: moment.Moment | null
  Q20tLastKey: moment.Moment | null
  Q20OverallTime: number | null
  Q20RecallTime: number | null
  Q20ReaderStart: moment.Moment | null
  Q20ReaderEnd: moment.Moment | null

  Q21ID: string | null
  Q21Response: string | null
  Q21InputMethods: string | null
  Q21K: string | null
  Q21Sco: number | null
  Q21ResponseTime: number | null
  Q21TimeOut: number | null
  Q21TimeOutResponse: number | null
  Q21TimeOutSco: number | null
  Q21tLoad: moment.Moment | null
  Q21tFirstKey: moment.Moment | null
  Q21tLastKey: moment.Moment | null
  Q21OverallTime: number | null
  Q21RecallTime: number | null
  Q21ReaderStart: moment.Moment | null
  Q21ReaderEnd: moment.Moment | null

  Q22ID: string | null
  Q22Response: string | null
  Q22InputMethods: string | null
  Q22K: string | null
  Q22Sco: number | null
  Q22ResponseTime: number | null
  Q22TimeOut: number | null
  Q22TimeOutResponse: number | null
  Q22TimeOutSco: number | null
  Q22tLoad: moment.Moment | null
  Q22tFirstKey: moment.Moment | null
  Q22tLastKey: moment.Moment | null
  Q22OverallTime: number | null
  Q22RecallTime: number | null
  Q22ReaderStart: moment.Moment | null
  Q22ReaderEnd: moment.Moment | null

  Q23ID: string | null
  Q23Response: string | null
  Q23InputMethods: string | null
  Q23K: string | null
  Q23Sco: number | null
  Q23ResponseTime: number | null
  Q23TimeOut: number | null
  Q23TimeOutResponse: number | null
  Q23TimeOutSco: number | null
  Q23tLoad: moment.Moment | null
  Q23tFirstKey: moment.Moment | null
  Q23tLastKey: moment.Moment | null
  Q23OverallTime: number | null
  Q23RecallTime: number | null
  Q23ReaderStart: moment.Moment | null
  Q23ReaderEnd: moment.Moment | null

  Q24ID: string | null
  Q24Response: string | null
  Q24InputMethods: string | null
  Q24K: string | null
  Q24Sco: number | null
  Q24ResponseTime: number | null
  Q24TimeOut: number | null
  Q24TimeOutResponse: number | null
  Q24TimeOutSco: number | null
  Q24tLoad: moment.Moment | null
  Q24tFirstKey: moment.Moment | null
  Q24tLastKey: moment.Moment | null
  Q24OverallTime: number | null
  Q24RecallTime: number | null
  Q24ReaderStart: moment.Moment | null
  Q24ReaderEnd: moment.Moment | null

  Q25ID: string | null
  Q25Response: string | null
  Q25InputMethods: string | null
  Q25K: string | null
  Q25Sco: number | null
  Q25ResponseTime: number | null
  Q25TimeOut: number | null
  Q25TimeOutResponse: number | null
  Q25TimeOutSco: number | null
  Q25tLoad: moment.Moment | null
  Q25tFirstKey: moment.Moment | null
  Q25tLastKey: moment.Moment | null
  Q25OverallTime: number | null
  Q25RecallTime: number | null
  Q25ReaderStart: moment.Moment | null
  Q25ReaderEnd: moment.Moment | null
}
