trigger: none

pool:
  name: 'MTC' # TODO set to MS managed

steps:
- script: az keyvault network-rule add --name $(KeyVaultInstance) --resource-group $(ResourceGroup) --ip-address $(ipAddress)
  displayName: 'Add IPv4 Address to KeyVault'
