resources:
- repo: self
  clean: true

jobs:

- job: Job_1
  displayName: prep sql
  condition: succeeded()
  pool:
    name: MTC LIVE
#Your build pipeline references an undefined variable named ‘RESOURCE_GROUP’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SQL_SERVER_SHORTNAME’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SQL_APP_USER_PASSWORD’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
  variables:
    SQL_DATABASE: 'mtc-dev'

  steps:
  - task: AzureCLI@1
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: 'MTC EE Dev'
      scriptLocation: inlineScript
      inlineScript: 'az sql db delete --name $(SQL_DATABASE) --resource-group $(RESOURCE_GROUP) --server $(SQL_SERVER_SHORTNAME) --yes'

  - task: Bash@3
    displayName: 'create db'
    inputs:
      targetType: ./
      filePath: 'deploy/sql-migrations/migrate-db.sh'
      arguments: '$(SQL_ADMIN_USER) $(SQL_ADMIN_USER_PASSWORD) $(SQL_APP_USER_PASSWORD)'


- job: Phase_1
  displayName: Run Pupil Tests
  dependsOn: Job_1
  condition: succeeded()
  pool:
    name: MTC LIVE
  steps:
  - bash: |
       source ~/.profile
       gem install bundler
       bundle install
       rake features
    workingDirectory: 'test/pupil-hpa'
    displayName: 'PUPIL: Run End to End Tests'

  - task: CopyFiles@2
    displayName: 'Copy screenshots to staging folder'
    inputs:
      SourceFolder: 'test/pupil-hpa'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/pupil-tests'
    condition: succeededOrFailed()

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.ArtifactStagingDirectory)/pupil-tests'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/pupil-tests'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: mtc-nightly-build-PUPIL'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'mtc-nightly-build-PUPIL'
    condition: succeededOrFailed()


- job: Phase_2
  displayName: Run Admin Tests
  dependsOn:
  - Job_1
  - Phase_1
  condition: succeeded()
  pool:
    name: MTC LIVE
  steps:
  - bash: |
       source ~/.profile
       gem install bundler
       bundle install
       rake features
    workingDirectory: 'test/admin-hpa'
    displayName: 'ADMIN: Run End to End Tests'

  - task: CopyFiles@2
    displayName: 'Copy screenshots to staging folder'
    inputs:
      SourceFolder: 'test/admin-hpa'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/admin-tests'
    condition: succeededOrFailed()

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.ArtifactStagingDirectory)/admin-tests'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/admin-tests'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: mtc-nightly-build'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'mtc-nightly-build-ADMIN'
    condition: succeededOrFailed()


- job: Job_2
  displayName: reset db
  condition: succeeded()
  pool:
    name: MTC LIVE
#Your build pipeline references an undefined variable named ‘RESOURCE_GROUP’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SQL_SERVER_SHORTNAME’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘SQL_APP_USER_PASSWORD’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
  variables:
    SQL_DATABASE: 'mtc-dev'

  steps:
  - task: AzureCLI@1
    displayName: 'delete db'
    inputs:
      azureSubscription: 'MTC EE Dev'
      scriptLocation: inlineScript
      inlineScript: 'az sql db delete --name $(SQL_DATABASE) --resource-group $(RESOURCE_GROUP) --server $(SQL_SERVER_SHORTNAME) --yes'

  - task: Bash@3
    displayName: 'create db'
    inputs:
      targetType: ./
      filePath: 'deploy/sql-migrations/migrate-db.sh'
      arguments: '$(SQL_ADMIN_USER) $(SQL_ADMIN_USER_PASSWORD) $(SQL_APP_USER_PASSWORD)'


