trigger: none

pool:
  name: 'Azure Pipelines'

steps:
- task: AzureCLI@2
  displayName: 'Remove Build Server IPv4 Address from PreProd KeyVault'
  inputs:
    azureSubscription: $(PreProdServiceConnection)
    scriptType: bash
    scriptPath: 'deploy/build-defs/remove-key-vault-ip.sh'
    arguments: $(PreProdKeyVaultName) $(PreProdResourceGroup) $(IpAddress)
- task: AzureCLI@2
  displayName: 'Remove Build Server IPv4 Address from Prod KeyVault'
  inputs:
    azureSubscription: $(ProdServiceConnection)
    scriptType: bash
    scriptPath: 'deploy/build-defs/remove-key-vault-ip.sh'
    arguments: $(ProdKeyVaultName) $(ProdResourceGroup) $(IpAddress)
