name: resetdb-$(date:yyyyMMdd)$(rev:.r)
resources:
- repo: self
  clean: true
  fetchDepth: 1

pool:
  name: MTC LIVE

variables:
  SQL_DATABASE:
  AZURE_SUBSCRIPTION:
  RESOURCE_GROUP:
  SQL_ADMIN_USER:
  SQL_ADMIN_USER_PASSWORD:
  SQL_APP_USER: 'mtcAdminUser' # default, sourced from config.js.  Does not need to be changed unless environment uses custom value
  SQL_APP_USER_PASSWORD:
  18K_SEED_ENABLED: false # override to true if you wish to seed the database with 18000 schools, teachers and 40 pupils per school

steps:
- task: AzureCLI@1
  displayName: 'Delete Existing Database'
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptLocation: inlineScript
    inlineScript: 'az sql db delete --name $(SQL_DATABASE) --resource-group $(RESOURCE_GROUP) --server $(SQL_SERVER_SHORTNAME) --yes'

- task: Bash@3
  displayName: 'create database'
  inputs:
    targetType: ./
    filePath: 'deploy/sql-migrations/migrate-db.sh'
    arguments: '$(SQL_ADMIN_USER) $(SQL_ADMIN_USER_PASSWORD) $(SQL_APP_USER_PASSWORD)'

- task: Bash@3
  displayName: 'seed database'
  inputs:
    targetType: ./
    filePath: 'deploy/sql-migrations/seed-db.sh'
    arguments: '$(SQL_ADMIN_USER) $(SQL_ADMIN_USER_PASSWORD) $(SQL_APP_USER_PASSWORD)'

- task: Bash@3
  displayName: 'Initialise 18K Teacher & Pupil Data'
  enabled: $(18K_SEED_ENABLED)
  inputs:
    targetType: ./
    filePath: 'load-test/load-18k-teacher-pupils.sh'
    workingDirectory: 'load-test'


