# AzureDevops build defintion for Azure services key rotation and key vault update
resources:
  - repo: self

name: Azure-Key-Rotation-$(date:yyyyMMdd)$(rev:.r)

# do not trigger on master commits
trigger: none

pool:
  name: MTC LIVE

jobs:
- job: RedisKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Redis Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/azure/key-vault/key-rotation/redis.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(RedisName) $(KeyType)
      failOnStandardError: true
- job: ServiceBusKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Service Bus Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/azure/key-vault/key-rotation/service-bus.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(ServiceBusName) $(KeyType) $(ServiceBusUser)
      failOnStandardError: true
- job: StorageAccountKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Storage Account Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/azure/key-vault/key-rotation/storage.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(StorageAccountName) $(KeyType)
      failOnStandardError: true
