# AzureDevops build defintion for Azure services key rotation and key vault update
resources:
  - repo: self

name: Azure-Key-Rotation-$(date:yyyyMMdd)$(rev:.r)

# do not trigger on master commits
trigger: none

pool:
  name: $(BuildAgentPool)
# schedules:
# - cron: "0 3 * * *"
#   displayName: "3am daily"
#   branches:
#     include:
#     - master
#     - /feature/46006-key-rotation-build-task
#   always: true

jobs:
- job: RedisKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Redis Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/key-rotation/redis.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(RedisName) $(KeyType)
      failOnStandardError: true
- job: ServiceBusKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Service Bus Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/key-rotation/service-bus.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(ServiceBusName) $(KeyType) $(ServiceBusUser)
      failOnStandardError: true
- job: StorageAccountKey
  steps:
  - task: AzureCLI@2
    displayName: Rotate Storage Account Key
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: bash
      scriptPath: 'deploy/key-rotation/storage.sh'
      arguments: $(ResourceGroupName) $(KeyVaultName) $(StorageAccountName) $(KeyType)
      failOnStandardError: true
