resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

# fast fail if no 'CI Enabled' label on PR
steps:
  displayName: 'Fail if CI Enabled label not applied to PR'
  - bash: |
      PR_ID=$(System.PullRequest.PullRequestNumber)
      PR_URL="https://api.github.com/repos/dfeagiledevops/mtc/pulls/$PR_ID"
      echo "looking up PR at $PR_URL"
      CURL_RESPONSE=$(curl -s $PR_URL | jq '.labels[] | select(.id==861719997) | .id')
      echo "response is $CURL_RESPONSE"
      if [ "$CURL_RESPONSE" -ne "861719997" ]; then
        exit 1;
      fi
    failOnStderr: true






