resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

variables:
  var1: value1

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

jobs:
- job: FastFail
  steps:
  - bash: 'deploy/pr-label-check.sh'
    env:
      PULL_REQUEST_ID: $(System.PullRequest.PullRequestNumber)
    failOnStderr: true
