resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

variables:
  var1: value1

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

jobs:
- job: FastFail
  steps:
  - task: Bash@3
    inputs:
      filePath: 'deploy/pr-label-check.sh'
      arguments: $PULL_REQUEST_ID
      failOnStderr: true
