resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

variables:
  var1: value1

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

jobs:
- job: FastFail
  steps:
    displayName: 'Fail if CI Enabled label not applied to PR'
    failOnStderr: true
    - bash: |
    PR_ID=$(System.PullRequest.PullRequestNumber)
    PR_URL="https://api.github.com/repos/dfeagiledevops/mtc/pulls/$PR_ID"
    echo "looking up PR at $PR_URL"
    CURL_RESPONSE=$(curl -s $PR_URL | jq '.labels[] | select(.id==861719997) | .id')
    echo "response is $CURL_RESPONSE"
    if [ "$CURL_RESPONSE" -ne "861719997" ]; then
    exit 1;
    fi
- job: BuildAdminImage
  dependsOn: FastFail
    steps:
      - task: ShellScript@2
      displayName: 'generate build and commit details file'
      inputs:
        scriptPath: 'admin/vso-add-build-and-commit.sh'
        failOnStandardError: true
#      - task: Docker@1
#      displayName: 'Create Image'
#      inputs:
#        azureSubscriptionEndpoint: 'MTC EE Dev'
#        azureContainerRegistry: ''
#        dockerFile: admin/Dockerfile
#        imageName: 'admin:$(Build.BuildNumber)'
#        includeSourceTags: true
#        includeLatestTag: true
