resources:
  - repo: self

name: PR-$(date:yyyyMMdd)$(rev:.r)

variables:
  var1: value1

trigger: none

pr: # triggered by new PR
  branches:
    include: [ master ]

pool:
  name: MTC LIVE

jobs:
- job: FastFail
  steps:
    - task: ShellScript@2
    displayName: 'Fail if CI Enabled label not applied to PR'
    inputs:
      scriptPath: '../pr-label-check.sh'
      failOnStandardError: true
- job: Generate
  dependsOn: FastFail
    steps:
      - task: ShellScript@2
      displayName: 'generate build and commit details file'
      inputs:
        scriptPath: 'admin/vso-add-build-and-commit.sh'
        failOnStandardError: true

