// one for each offset
export const timezones = [
  { name: 'International Day Line West', offset: '-12' },
  { name: 'New Zealand Standard Time', offset: '-11' },
  { name: 'Samoa Standard Time', offset: '-10' },
  { name: 'Alaska Standard Time', offset: '-9' },
  { name: 'Clipperton Island Standard Time', offset: '-8' },
  { name: 'Mountain Standard Time', offset: '-7' },
  { name: 'Central Standard Time', offset: '-6' },
  { name: 'Cuba Standard Time', offset: '-5' },
  { name: 'Colombia Summer Time', offset: '-4' },
  { name: 'Chile Summer Time', offset: '-3' },
  { name: 'Fernando de Noronha Time', offset: '-2' },
  { name: 'Azores Standard Time', offset: '-1' },
  { name: 'Central European Time', offset: '1' },
  { name: 'Eastern European Time', offset: '2' },
  { name: 'Further-eastern European Time', offset: '3' },
  { name: 'Georgia Standard Time', offset: '4' },
  { name: 'Mawson Station Time', offset: '5' },
  { name: 'British Indian Ocean Time', offset: '6' },
  { name: 'Christmas Island Time', offset: '7' },
  { name: 'China Time', offset: '8' },
  { name: 'Eastern Indonesian Time', offset: '9' },
  { name: 'Papua New Guinea Time', offset: '10' },
  { name: 'Pohnpei Standard Time', offset: '11' },
  { name: 'Tuvalu Time', offset: '12' },
  { name: 'Phoenix Island Time', offset: '13' },
  { name: 'Line Islands Time', offset: '14' }
]
