// one for each offset
export const timezones = [
  { 'International Day Line West': '-12' },
  { 'New Zealand Standard Time': '-11' },
  { 'Samoa Standard Time': '-10' },
  { 'Alaska Standard Time': '-9' },
  { 'Clipperton Island Standard Time': '-8' },
  { 'Mountain Standard Time': '-7' },
  { 'Central Standard Time': '-6' },
  { 'Cuba Standard Time': '-5' },
  { 'Colombia Summer Time': '-4' },
  { 'Chile Summer Time': '-3' },
  { 'Fernando de Noronha Time': '-2' },
  { 'Azores Standard Time': '-1' },
  { 'Central European Time': '1' },
  { 'Eastern European Time': '2' },
  { 'Further-eastern European Time': '3' },
  { 'Georgia Standard Time': '4' },
  { 'Mawson Station Time': '5' },
  { 'British Indian Ocean Time': '6' },
  { 'Christmas Island Time': '7' },
  { 'China Time': '8' },
  { 'Eastern Indonesian Time': '9' },
  { 'Papua New Guinea Time': '10' },
  { 'Pohnpei Standard Time': '11' },
  { 'Tuvalu Time': '12' },
  { 'Phoenix Island Time': '13' },
  { 'Line Islands Time': '14' }
]
